INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (1, 51202, 'Drakova 1', 'Hradec Králové', 'Czech Republic');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (2, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (3, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (4, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (5, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (6, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (1006, 51200, 'K Lopatě', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.address__address (id, zip, street, city, state) VALUES (1008, 51200, 'K Zahradě 5', 'Hradec Králové', 'CR');
INSERT INTO tnpw_eam.dbo.controls__category (id, title, description, deletable) VALUES (1, 'Nekategorizováno', 'Kontrola není nijak kategorizovaná', 0);
INSERT INTO tnpw_eam.dbo.controls__category (id, title, description, deletable) VALUES (3, 'Povinná záruční', 'Kontrola podmíněná záručními podmínkami', 1);
INSERT INTO tnpw_eam.dbo.controls__category (id, title, description, deletable) VALUES (4, 'Preventivní', 'Preventivní kontrola (náhodná)', 1);
INSERT INTO tnpw_eam.dbo.controls__status (id, title, description, deletable) VALUES (1, 'Nekategorizováno', 'Kontrola není nijak kategorizovaná', 0);
INSERT INTO tnpw_eam.dbo.controls__status (id, title, description, deletable) VALUES (2, 'Naplánována', 'Kontrola je naplánována', 1);
INSERT INTO tnpw_eam.dbo.controls__status (id, title, description, deletable) VALUES (3, 'Právě prováděna', 'Kontrola se právě provádí (horizont jednoho až tří dnů)', 1);
INSERT INTO tnpw_eam.dbo.controls__status (id, title, description, deletable) VALUES (4, 'Provedena', 'Kontrola byla provedena', 1);
INSERT INTO tnpw_eam.dbo.controls__status (id, title, description, deletable) VALUES (5, 'Archivováno', 'Záznam o kontrole byl archivován', 0);
INSERT INTO tnpw_eam.dbo.environments__category (id, title, description, deletable) VALUES (1, 'Nekategorizováno', 'Prostředí není nijak kategorizovano', 0);
INSERT INTO tnpw_eam.dbo.environments__category (id, title, description, deletable) VALUES (2, 'Budova', 'Klasická budova', 1);
INSERT INTO tnpw_eam.dbo.environments__category (id, title, description, deletable) VALUES (3, 'Exteriér', 'Exteriér (pozemek)', 1);
INSERT INTO tnpw_eam.dbo.environments__category (id, title, description, deletable) VALUES (4, 'Sportoviště', 'Prostředí sportoviště', 1);
INSERT INTO tnpw_eam.dbo.environments__environment (id, name, description, bussiness_id, address_id, category_id, code) VALUES (2, 'Skladiště 1', '12456', null, 1006, null, '1C');
INSERT INTO tnpw_eam.dbo.environments__environment (id, name, description, bussiness_id, address_id, category_id, code) VALUES (4, 'Výrobní hala 2', 'gfds', null, 1008, null, 'gfds');
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (3, 'Nekategorizováno', 'Vybavení není nijak kategorizovano', 0);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (4, 'Elektronika', 'Elektronické vybavení', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (5, 'Nábytek', 'Obecně všechno (židle, stoly)', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (6, 'Dekorace', 'Dekorace', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (7, 'Osvětlení', 'Světla na chodbách a jiné', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (8, 'Krytiny', 'Koberce, parkety atd.', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (9, 'Rozvody', 'Technické věci kolem rozvodů vody, elektroniky a plynu', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (10, 'Vodovodní zařízení', 'Technické věci kolem distribuce vody', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (11, 'Sanitární zařízení', 'WC, umyvadla ...', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (12, 'Topná zařízení', 'Kotle, rozvody plynu...', 1);
INSERT INTO tnpw_eam.dbo.equipments__category (id, title, description, deletable) VALUES (13, 'Okna a dveře', 'Okna a dveře', 1);
INSERT INTO tnpw_eam.dbo.equipments__equipment (id, title, description, purchased, warranty, status_id, room_id, category_id, code) VALUES (4, 'gfds', 'ges', '2019-03-07 00:00:00.000', '2019-03-15 00:00:00.000', 1, 1002, null, 'trtr');
INSERT INTO tnpw_eam.dbo.equipments__equipment (id, title, description, purchased, warranty, status_id, room_id, category_id, code) VALUES (5, 'Kotel', 'fdfd', '2019-03-13 00:00:00.000', '2019-03-27 00:00:00.000', 1, 5, 3, 'fdf');
INSERT INTO tnpw_eam.dbo.equipments__status (id, title, description, deletable) VALUES (1, 'Nekategorizováno', 'Stav není nijak kategorizovan', 0);
INSERT INTO tnpw_eam.dbo.equipments__status (id, title, description, deletable) VALUES (2, 'Funkční', 'Zařízení je plně funkční', 0);
INSERT INTO tnpw_eam.dbo.equipments__status (id, title, description, deletable) VALUES (3, 'Rozbité (problém se řeší)', 'Zařízení je rozbité a jeho napravení je aktuálně přiděleno nějakému opraváři', 0);
INSERT INTO tnpw_eam.dbo.equipments__status (id, title, description, deletable) VALUES (4, 'Rozbité (problém se zatím neřeší)', 'Zařízení je rozbité, ale zatím se k tomu nikdo nedostal', 0);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (1, 'Nekategorizováno', 'Místnost není nijak kategorizovana', 0);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (2, 'Učebna', 'Místnost sloužící k výuce', 1);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (3, 'Technické zázemí', 'Místnost pro technické zázemí', 1);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (4, 'Kancelář', 'Místnost pro administrativní účely', 1);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (5, 'Chodba', 'Chodba propojující další místnosti', 1);
INSERT INTO tnpw_eam.dbo.rooms__category (id, title, description, deletable) VALUES (6, 'Společné prostory', 'Místnost sloužící pro více lidí', 1);
INSERT INTO tnpw_eam.dbo.rooms__room (id, name, purpouse, code, floor, environment_id, category_id) VALUES (4, 'J2', 'kk', 'k', 1, 4, null);
INSERT INTO tnpw_eam.dbo.rooms__room (id, name, purpouse, code, floor, environment_id, category_id) VALUES (5, 'J3', 'pp', 'oo', 1, 4, null);
INSERT INTO tnpw_eam.dbo.rooms__room (id, name, purpouse, code, floor, environment_id, category_id) VALUES (1002, 'Interiér', 'Interier skladiště', 'fdsa', 1, 2, null);
INSERT INTO tnpw_eam.dbo.tickets__category (id, title, description, color_class, deletable, impact) VALUES (2, 'Nekategorizováno', 'Problém není nijak kategorizovan', 'info', 0, 0);
INSERT INTO tnpw_eam.dbo.tickets__category (id, title, description, color_class, deletable, impact) VALUES (3, 'Může počkat', 'O problému se ví, ale není třeba ho řešit v krátkodobém horizontu', 'success', 1, 10);
INSERT INTO tnpw_eam.dbo.tickets__category (id, title, description, color_class, deletable, impact) VALUES (4, 'Je třeba řešit', 'O problému se ví a je třeba ho řešit v krátkodobém horizontu', 'warning', 1, 20);
INSERT INTO tnpw_eam.dbo.tickets__category (id, title, description, color_class, deletable, impact) VALUES (5, 'Naléhavé', 'Problém je třeba vyřešit ihned!', 'danger', 1, 30);
INSERT INTO tnpw_eam.dbo.tickets__status (id, title, description, deletable, color_class) VALUES (1, 'Řeší se', 'Problém je aktuálně řešen', 0, 'info');
INSERT INTO tnpw_eam.dbo.tickets__status (id, title, description, deletable, color_class) VALUES (2, 'Řešení naplánováno a přiřazeno', 'Řešení problému je přiřazeno pracovníkovi', 0, 'primary');
INSERT INTO tnpw_eam.dbo.tickets__status (id, title, description, deletable, color_class) VALUES (3, 'Pouze zaznamenáno', 'O problému se ví, ale nikdo k němu nebyl přidělen', 0, 'warning');
INSERT INTO tnpw_eam.dbo.tickets__status (id, title, description, deletable, color_class) VALUES (4, 'Vyřešeno', 'Problém byl vyřešen', 0, 'success');
INSERT INTO tnpw_eam.dbo.tickets__status (id, title, description, deletable, color_class) VALUES (5, 'Archivováno', 'Záznam je archivován', 0, 'primary');
INSERT INTO tnpw_eam.dbo.tickets__ticket (id, title, description, equipment_id, author_id, solver_id, assigned_id, status_id, category_id, created, deadline) VALUES (5, 'Nefunguje kohoutek', 'ooo', null, null, null, null, null, null, '2019-03-26 14:45:42.700', null);
INSERT INTO tnpw_eam.dbo.users__role (id, title, description) VALUES (1, 'admin', 'He has all the privililages and he can enter every section of the app');
INSERT INTO tnpw_eam.dbo.users__user (id, name, surname, password, email, role_id, phone, address_id, deletable) VALUES (1, 'Adam', 'Ouhrabka', '930318', 'adam.ouhrabka@gmail.com', 1, '776485123', null, 1);
INSERT INTO tnpw_eam.dbo.users__user (id, name, surname, password, email, role_id, phone, address_id, deletable) VALUES (2, 'Tomáš', 'Tremp', '930318', 'tomas.tremp@gmail.com', 1, '775468154', null, 1);